# Generated by Django 5.1.3 on 2024-12-07 18:36

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('about', '0002_sociallinks'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='sociallinks',
            options={'verbose_name_plural': 'Social Link'},
        ),
    ]
